### ISSUE TITLE
Question: Is "DateTime" name a bad practice?

### ISSUE THREAD

**Issue by danschmidt5189** [tobyink/p5-types-xsd#1]
I noticed that `Types::XSD` exports a `DateTime` type which matches ISO8601-formatted datetime strings. I recall reading in one of the docs that it is bad practice to give a type the name of an existing class - in this case, [DateTime](https://metacpan.org/pod/DateTime) - since this is ambiguous.

What's the author's opinion on this?

(Aside - I'm working on best practices for a large-ish Perl development team, and this is one of our sticking points.)

**Comment by tobyink** [comment]
It uses the name "DateTime" because that matches the name in the XSD specification. But you can rename types when you export them. For example:

```
use Types::XSD { prefix => "xs_" }, -types;

has start_date => ( is => "ro", isa => xs_DateTime, required => 1 );
```

**Comment by tobyink** [comment]
See also:
http://search.cpan.org/~tobyink/Exporter-Tiny-0.043_01/lib/Exporter/Tiny/Manual/Importing.pod
